"""Initial database

Revision ID: ca3e94739bfc
Revises: 
Create Date: 2025-06-18 21:53:08.909268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3e94739bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palindromes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('is_palindrome', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('palindromes', schema=None) as batch_op:
        batch_op.create_index('idx_language', ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_palindromes_language'), ['language'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palindromes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_palindromes_language'))
        batch_op.drop_index('idx_language')

    op.drop_table('palindromes')
    # ### end Alembic commands ###
